### ISSUE TITLE
Description of App & Sketch

### ISSUE THREAD

**Issue by berkaybulut** [UBC-MDS/532Group4#4]

**Comment by AraiYuno** [comment]
Based on the dataset and usage scenarios, this is an initial draft that I quickly sketch!
![image](https://user-images.githubusercontent.com/28745975/154602125-76ff4000-9a30-41f4-bdf7-95dd63a4627c.png)
I like filtering options at the top right corner and maybe the title on the top centre.
Visualizations can be changed.
